spring:
  mvc:
    pathmatch:
      use-suffix-pattern: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  datasource:
    url: ${SPRING_DATASOURCE_URL:marketprimebd}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: "${SPRING_DATASOURCE_PASSWORD:root}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

app:
  jwt:
    secret: ${JWT_SECRET:example-super-secret-for-marketprime-application}
    access-token-expiration-ms: 3600000
    refresh-token-expiration-ms: 604800000

aws:
  region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:dummy}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:dummy}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:dummy}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
